// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxJVxSoDVdcOoCxxN53aC1zUa60qQsfYw',
    appId: '1:1021391864709:web:0195f7ff2e703ba11c7aec',
    messagingSenderId: '1021391864709',
    projectId: 'overtimed',
    authDomain: 'overtimed.firebaseapp.com',
    storageBucket: 'overtimed.appspot.com',
    measurementId: 'G-G2XY8GJVE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshHy9bc9elC2YadOoj1sLmIHuUmdYGuo',
    appId: '1:1021391864709:android:c585b77cc6441c2f1c7aec',
    messagingSenderId: '1021391864709',
    projectId: 'overtimed',
    storageBucket: 'overtimed.appspot.com',
  );
}
